import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import Nav from "../components/Nav";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Visual Algorithms</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex min-h-screen flex-col">
        <Nav />
        <header className="container my-12 mx-auto flex flex-1 flex-col items-center justify-center">
          <h1 className="text-center text-9xl leading-tight tracking-tight text-zinc-300">
            visualize every algorithm with{" "}
            <span className="text-emerald-600"> ease.</span>
          </h1>
          <p className="font-Gilroy-Regular my-8 text-center text-3xl">
            View top algorithms step-by-step with complete code and diagram
          </p>
          <Link href="/explore">
            <a className="font-Gilroy-Bold mx-auto mt-8 block w-max rounded-full bg-emerald-600 px-16 py-5 text-center text-3xl font-medium">
              Explore
            </a>
          </Link>
        </header>
      </div>
    </>
  );
};

export default Home;
